version: '3.8'

services:
  frontend:
    image: frontendgodocapi:latest
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app-net

  backend:
    image: godocapi:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app-net

networks:
  app-net:
    driver: overlay
